### ISSUE TITLE
3.3.1 (master) source is not 3.3.1

### ISSUE THREAD

**Issue by r4dius** [Root-MtX/Nro2Nsp#10]
Not sure why but when I download the latest 3.3.1 source it's actually 3.2.2 version with the old pre-retroarch options

**Comment by Root-MtX** [comment]
Source wasn’t committed unfortunately, I started messing around a special batch build that I have publicly releaese yet and didn’t make a proper backup of my source as I usually do. It’ll be updated next stable build
