### ISSUE TITLE
Exit to redirected app causes crash

### ISSUE THREAD

**Issue by r4dius** [Root-MtX/Nro2Nsp#12]
Hi, sorry for the double submit,
I just tested the latest v3.3.2 Beta 2 on 6.2 with sx os 2.5.3 and I'm getting crashes when : 
I'm redirecting to hbmenu (latest version, sdmc redirect) -> then I run some app like checkpoint -> then exit the app with "+" -> I'm supposed to exit back to hbmenu but I get a console crash and I need to reboot :/
Got the crash every time I tried,
the nologo option works nice btw, thanks :)

**Comment by Root-MtX** [comment]
I’ll try this out but it may be due to when exiting the application, it’s trying to close the nsp. You cannot close a nsp within the code (or else it’ll crash the system) and you must use the home button. Trying leaving the app with the home button and closing it with (x)

**Comment by r4dius** [comment]
I tried with an older nsp (redirect too) I got from gbatemp and the problem doesn't happen with it but I've no idea how it was made, I can always leave any app with home or the app exit button and get back to hbmenu with no problem

**Comment by Root-MtX** [comment]
Do you have a link, I can investigate

**Comment by r4dius** [comment]
Can't find the original gbatemp post but here's the one I use http://r4di.us/temp/hbmenu_hbl2.zip

**Comment by Kronos2308** [comment]
yep i have that problem to i try to make a forwader for the hBMenu but crash wen you try to return to them by exit

**Comment by Root-MtX** [comment]
My network shit the bed and just got it somewhat up again, ill try and figure out a solution soon

**Comment by Kronos2308** [comment]
No presion ,,,thanks for your work

**Comment by Root-MtX** [comment]
I have fixed this, should return to hbmenu once leaving now. I just need to make sure I didn't break anything and add something else. Hopefully ill push a new beat release out tonight or tomorrow.

**Comment by Root-MtX** [comment]
New Beta is up, Should work properly now. Let me know if for some reason it doesnt!

**Comment by r4dius** [comment]
Works great for me, thanks ;)
