### ISSUE TITLE
Icons not displaying

### ISSUE THREAD

**Issue by thebdizzle** [Root-MtX/Nro2Nsp#14]
I'm having an issue where any custom icons, even if they are jpg's at 256 x 256 aren't displaying on the switch menu. The NSP's install fine, and the icon displays in tinfoil - but on the home screen they are just a question mark. The apps do open and redirect to the roms fine though. Any of the thumbnails from the community are fine. But even if I use these as a base in photoshop to put my image in place of, they still don't work. Any ideas? Thanks. Great app though!

**Comment by Root-MtX** [comment]
Are you using 3.3.3?

**Comment by thebdizzle** [comment]
Yes, 3.3.3. Tried on both windows and os x with the same result. Here are two of the images if you are able to reproduce the issue -
![Tetris_ _Dr_Mario_Title](https://user-images.githubusercontent.com/6408066/55180924-ac7d6780-51de-11e9-9486-8126e91c6224.png)
![iog](https://user-images.githubusercontent.com/6408066/55180977-c6b74580-51de-11e9-8ba2-4cce05593c6b.jpg)

**Comment by Root-MtX** [comment]
The problem is probably the images colour representation, you could get it to work by using paint or another image program and save as a bmp and then resave as jpg. I’ll take a look once I’m home with those images. It should check the color representation and concert as needed but maybe there’s a bug in it.

**Comment by Root-MtX** [comment]
Does the log file in the resources folder say anything about about the image information?

**Comment by thebdizzle** [comment]
The only thing in the log about the image is it loading it and removing exif data.

Here are my logs if it helps.

`--------------------------
Preset Settings:
Preset Author Enable: False
Preset Authot Value: 
Rolling Id Enable: False
Rolling Id Value: 
Perserve Data Enable: False
Key Generation: 1
--------------------------
Inputed Image Information:
Img Path: W:\Custom\Billy\iog.jpg
Image Extension type: .jpg
Icon Dimensions: 256x256
Removing any Exif Data...
--------------------------
Post Build:
Preset Author Enable: False
Preset Authot Value: 
Rolling Id Enable: False
Rolling Id Value: 
Perserve Data Enable: False
Key Generation: 1
--------------------------
Keys loaded from : ./Resources/prod.keys
--------------------------
App Name = iog
Author = dar
Version =  1.0.1
Title Id = 05CDD128249B0000
Standard Forwarder = False
Retro Rom Forwarder = True
Line = 
SdmcPath = /switch/application/application.nro
RomfsPath = /application.nro
Core Path = /retroarch/cores/o2em_libretro_libnx.nro
Rom Path = /roms/Bandai - WonderSwan Color/vg.zip
NroName = 
NroPath = 

--------------------------
C:\Nro2Nsp/temp/hacbrewpack.exe
C:\Nro2Nsp/temp/keys.dat
C:\Nro2Nsp/temp/control\control.nacp
C:\Nro2Nsp/temp/control\icon_AmericanEnglish.dat
C:\Nro2Nsp/temp/exefs\main
C:\Nro2Nsp/temp/exefs\main.npdm
C:\Nro2Nsp/temp/logo\NintendoLogo.png
C:\Nro2Nsp/temp/logo\StartupMovie.gif
C:\Nro2Nsp/temp/romfs\errorConsole.nro
C:\Nro2Nsp/temp/romfs\nextArgv
C:\Nro2Nsp/temp/romfs\nextNroPath

hacBrewPack v2.05 by The-4n

Removing existing temp and nca directories
Creating temp, nca and nsp directories
Loading 'C:\Nro2Nsp/temp/keys.dat' keyset file

----> Processing NPDM
Validating NPDM
Getting TitleID
Validating TitleID
Warning: TitleID 5cdd128249b0000 is greater than 01ffffffffffffff and it's not suggested

----> Processing NACP
Validating Title Name
Validating Title Publisher
Changing logo handeling to auto
Writing control.nacp

----> Creating Program NCA:
===> Creating NCA header
Writing NCA header placeholder to C:\Nro2Nsp/temp/nca\program.nca

---> Creating Section 0:
===> Building ExeFS
Writing C:\Nro2Nsp/temp/exefs\main to C:\Nro2Nsp/temp/raw\program_sec0_exefs
Writing C:\Nro2Nsp/temp/exefs\main.npdm to C:\Nro2Nsp/temp/raw\program_sec0_exefs
Calculating hash table

===> Writing ExeFS
Writing PFS0 hash table
Writing PFS0

===> Calculating Hashes:
Calculating Master hash
Calculating Section hash

---> Creating Section 1:
===> Building RomFS
Visiting directories
Calculating metadata
Writing C:\Nro2Nsp/temp/romfs/\errorConsole.nro to C:\Nro2Nsp/temp/raw\program_sec1_ivfc_lvl6
Writing C:\Nro2Nsp/temp/romfs/\nextArgv to C:\Nro2Nsp/temp/raw\program_sec1_ivfc_lvl6
Writing C:\Nro2Nsp/temp/romfs/\nextNroPath to C:\Nro2Nsp/temp/raw\program_sec1_ivfc_lvl6

===> Creating IVFC levels
Writing C:\Nro2Nsp/temp/raw\program_sec1_ivfc_lvl5
Writing C:\Nro2Nsp/temp/raw\program_sec1_ivfc_lvl4
Writing C:\Nro2Nsp/temp/raw\program_sec1_ivfc_lvl3
Writing C:\Nro2Nsp/temp/raw\program_sec1_ivfc_lvl2
Writing C:\Nro2Nsp/temp/raw\program_sec1_ivfc_lvl1

===> Writing IVFC levels
Writing C:\Nro2Nsp/temp/raw\program_sec1_ivfc_lvl1 to C:\Nro2Nsp/temp/nca\program.nca
Writing C:\Nro2Nsp/temp/raw\program_sec1_ivfc_lvl2 to C:\Nro2Nsp/temp/nca\program.nca
Writing C:\Nro2Nsp/temp/raw\program_sec1_ivfc_lvl3 to C:\Nro2Nsp/temp/nca\program.nca
Writing C:\Nro2Nsp/temp/raw\program_sec1_ivfc_lvl4 to C:\Nro2Nsp/temp/nca\program.nca
Writing C:\Nro2Nsp/temp/raw\program_sec1_ivfc_lvl5 to C:\Nro2Nsp/temp/nca\program.nca
Writing C:\Nro2Nsp/temp/raw\program_sec1_ivfc_lvl6 to C:\Nro2Nsp/temp/nca\program.nca

===> Calculating Hashes:
Calculating Master hash
Calculating Section hash

---> Creating Section 2:
===> Building PFS0
Writing C:\Nro2Nsp/temp/logo/\NintendoLogo.png to C:\Nro2Nsp/temp/raw\program_sec2_logo
Writing C:\Nro2Nsp/temp/logo/\StartupMovie.gif to C:\Nro2Nsp/temp/raw\program_sec2_logo
Calculating hash table

===> Writing IVFC levels
Writing PFS0 hash table
Writing PFS0

===> Calculating Hashes:
Calculating Master hash
Calculating Section hash

---> Finalizing:
===> Encrypting NCA
Encrypting section 0
Encrypting section 1
Getting NCA file size
Encrypting key area
Encrypting header

===> Writing NCA header
Writing NCA header to C:\Nro2Nsp/temp/nca\program.nca

===> Post creation process
Calculating NCA hash
Renaming program.nca to 3bfbd263eb30664b59327ea876165d5c.nca

----> Created Program NCA: C:\Nro2Nsp/temp/nca\3bfbd263eb30664b59327ea876165d5c.nca

----> Creating Control NCA:
===> Creating NCA header
Writing NCA header placeholder to C:\Nro2Nsp/temp/nca\control.nca

---> Creating Section 0:
===> Building RomFS
Visiting directories
Calculating metadata
Writing C:\Nro2Nsp/temp/control/\control.nacp to C:\Nro2Nsp/temp/raw\control_sec0_ivfc_lvl6
Writing C:\Nro2Nsp/temp/control/\icon_AmericanEnglish.dat to C:\Nro2Nsp/temp/raw\control_sec0_ivfc_lvl6

===> Creating IVFC levels
Writing C:\Nro2Nsp/temp/raw\control_sec0_ivfc_lvl5
Writing C:\Nro2Nsp/temp/raw\control_sec0_ivfc_lvl4
Writing C:\Nro2Nsp/temp/raw\control_sec0_ivfc_lvl3
Writing C:\Nro2Nsp/temp/raw\control_sec0_ivfc_lvl2
Writing C:\Nro2Nsp/temp/raw\control_sec0_ivfc_lvl1

===> Writing IVFC levels
Writing C:\Nro2Nsp/temp/raw\control_sec0_ivfc_lvl1 to C:\Nro2Nsp/temp/nca\control.nca
Writing C:\Nro2Nsp/temp/raw\control_sec0_ivfc_lvl2 to C:\Nro2Nsp/temp/nca\control.nca
Writing C:\Nro2Nsp/temp/raw\control_sec0_ivfc_lvl3 to C:\Nro2Nsp/temp/nca\control.nca
Writing C:\Nro2Nsp/temp/raw\control_sec0_ivfc_lvl4 to C:\Nro2Nsp/temp/nca\control.nca
Writing C:\Nro2Nsp/temp/raw\control_sec0_ivfc_lvl5 to C:\Nro2Nsp/temp/nca\control.nca
Writing C:\Nro2Nsp/temp/raw\control_sec0_ivfc_lvl6 to C:\Nro2Nsp/temp/nca\control.nca

===> Calculating Hashes:
Calculating Master hash
Calculating Section hash

---> Finalizing:
===> Encrypting NCA
Encrypting section 0
Getting NCA file size
Encrypting key area
Encrypting header

===> Writing NCA header
Writing NCA header to C:\Nro2Nsp/temp/nca\control.nca

===> Post creation process
Calculating NCA hash
Renaming control.nca to 7236f5939b4f9632246a11f5f808ee8d.nca

----> Created Control NCA: C:\Nro2Nsp/temp/nca\7236f5939b4f9632246a11f5f808ee8d.nca

----> Creating Metadata NCA:
===> Creating NCA header
Writing NCA header placeholder to C:\Nro2Nsp/temp/nca\meta.nca

===> Creating Metadata file
Writing metadata header
Writing content records

===> Building PFS0
Writing C:\Nro2Nsp/temp/raw\cnmt\Application_05cdd128249b0000.cnmt to C:\Nro2Nsp/temp/raw\meta_sec0_pfs0
Calculating hash table

===> Writing PFS0 section
Writing PFS0 hash table
Writing PFS0

===> Calculating Hashes:
Calculating Master hash
Calculating Section hash

---> Finalizing:
===> Encrypting NCA
Encrypting section 0
Getting NCA file size
Encrypting key area
Encrypting header

===> Writing NCA header
Writing NCA header to C:\Nro2Nsp/temp/nca\meta.nca

===> Post creation process
Calculating NCA hash
Renaming meta.nca to 47bf7f2cfd826ff476a0cea3a1a492e3.cnmt.nca

----> Created Metadata NCA: C:\Nro2Nsp/temp/nca\47bf7f2cfd826ff476a0cea3a1a492e3.cnmt.nca

----> Creating NSP:
Writing C:\Nro2Nsp/temp/nca\3bfbd263eb30664b59327ea876165d5c.nca to C:\Nro2Nsp/temp/\05cdd128249b0000.nsp
Writing C:\Nro2Nsp/temp/nca\47bf7f2cfd826ff476a0cea3a1a492e3.cnmt.nca to C:\Nro2Nsp/temp/\05cdd128249b0000.nsp
Writing C:\Nro2Nsp/temp/nca\7236f5939b4f9632246a11f5f808ee8d.nca to C:\Nro2Nsp/temp/\05cdd128249b0000.nsp

----> Created NSP: C:\Nro2Nsp/temp/\05cdd128249b0000.nsp

Removing created temp directory


Summary:

Title ID: 05cdd128249b0000
SDK Version: 0.12.17.0
Section Crypto Type: Regular Crypto
Keygeneration: 1
Key area key 2: 04040404040404040404040404040404
Program NCA RomFS Section: Yes
Program NCA Logo Section: Yes
HtmlDoc NCA: No
Created NSP: C:\Nro2Nsp/temp/\05cdd128249b0000.nsp

[WARN]: Failed to match key "bis_kek_source", (value "34c1a0c48258f8b4fa9e5e6adafc7e4f")
[WARN]: Failed to match key "bis_key_00", (value "b9231dbed4ad31a85e496002b5cf1cef8fa5555be945ed46360186ade22fa23f")
[WARN]: Failed to match key "bis_key_01", (value "b96fca61414189dd583cf689b50224c30a8702ce49cf5a0575e3f75b08d5c39c")
[WARN]: Failed to match key "bis_key_02", (value "9acde63143c2b5943b0f876c04e03617927b14307613bb3cfd492c45a57ceeb3")
[WARN]: Failed to match key "bis_key_03", (value "9acde63143c2b5943b0f876c04e03617927b14307613bb3cfd492c45a57ceeb3")
[WARN]: Failed to match key "bis_key_source_00", (value "f83f386e2cd2ca32a89ab9aa29bfc7487d92b03aa8bfdee1a74c3b6e35cb7106")
[WARN]: Failed to match key "bis_key_source_01", (value "41003049ddccc065647a7eb41eed9c5f44424edab49dfcd98777249adc9f7ca4")
[WARN]: Failed to match key "bis_key_source_02", (value "52c2e9eb09e3ee2932a10c1fb6a0926c4d12e14b2a474c1c09cb0359f015f4e4")
[WARN]: Failed to match key "device_key", (value "124f988885dd3cd4b530267a8bd8dfba")
[WARN]: Failed to match key "eticket_rsa_kek", (value "19c8b441d318802bad63a5beda283a84")
[WARN]: Failed to match key "eticket_rsa_kek_source", (value "dba451124ca0a9836814f5ed95e3125b")
[WARN]: Failed to match key "eticket_rsa_kekek_source", (value "466e57b74a447f02f321cde58f2f5535")
[WARN]: Failed to match key "per_console_key_source", (value "4f025f0eb66d110edc327d4186c2f478")
[WARN]: Failed to match key "retail_specific_aes_key_source", (value "e2d6b87a119cb880e822888a46fba195")
[WARN]: Failed to match key "rsa_oaep_kek_generation_source", (value "a8ca938434127fda82cc1aa5e807b112")
[WARN]: Failed to match key "rsa_private_kek_generation_source", (value "ef2cb61a56729b9157c38b9316784ddd")
[WARN]: Failed to match key "save_mac_key", (value "7964d664c62f8c506a5080eb4ec6cfb4")
[WARN]: Failed to match key "sd_seed", (value "509293cd4e5583f12a8685a702d973af")
[WARN]: Failed to match key "ssl_rsa_kek", (value "b011100660d1dccbad1b1b733afa9f95")
[WARN]: Failed to match key "ssl_rsa_kek_source_x", (value "7f5bb0847b25aa67fac84be23d7b6903")
[WARN]: Failed to match key "ssl_rsa_kek_source_y", (value "9a383bf431d0bd8132534ba964397de3")

--------------------------
C:\Nro2Nsp/temp/05cdd128249b0000.nsp
C:\Nro2Nsp/temp/hacbrewpack.exe
C:\Nro2Nsp/temp/keys.dat
C:\Nro2Nsp/temp/control\control.nacp
C:\Nro2Nsp/temp/control\icon_AmericanEnglish.dat
C:\Nro2Nsp/temp/exefs\main
C:\Nro2Nsp/temp/exefs\main.npdm
C:\Nro2Nsp/temp/logo\NintendoLogo.png
C:\Nro2Nsp/temp/logo\StartupMovie.gif
C:\Nro2Nsp/temp/nca\3bfbd263eb30664b59327ea876165d5c.nca
C:\Nro2Nsp/temp/nca\47bf7f2cfd826ff476a0cea3a1a492e3.cnmt.nca
C:\Nro2Nsp/temp/nca\7236f5939b4f9632246a11f5f808ee8d.nca
C:\Nro2Nsp/temp/romfs\errorConsole.nro
C:\Nro2Nsp/temp/romfs\nextArgv
C:\Nro2Nsp/temp/romfs\nextNroPath

--------------------------
Read nextNroPath: |sdmc:/retroarch/cores/o2em_libretro_libnx.nro|
Read nextArgv: |sdmc:/retroarch/cores/o2em_libretro_libnx.nro "sdmc:/roms/Bandai - WonderSwan Color/vg.zip"|

--------------------------
Post Build:
Preset Author Enable: False
Preset Authot Value: 
Rolling Id Enable: False
Rolling Id Value: 
Perserve Data Enable: False
Key Generation: 1
`

**Comment by thebdizzle** [comment]
Running it through paint and converting to bitmap first fixed it!

This issue can be closed. Thank you so much for the help. Amazing app.
