### ISSUE TITLE
Temp dir location

### ISSUE THREAD

**Issue by joemck** [Root-MtX/Nro2Nsp#16]
I have noticed that this uses a hardcoded temp path of \Nro2Nsp, in the root of the drive that it's run from. I noticed this because I put it into D:\nro2nsp (on my data drive) and watched as it deleted most of its files and then errored out when it tried to delete MtX.Control.dll and couldn't because it was in use. I see that this could cause permission issues for anyone who doesn't have permission to write to the root of their drive, such as a limited Windows account or a Linux or Mac user running it in Wine.

I propose instead using a directory named nro2nsp.tmp either inside the current directory, or in the user's temp folder, which can be found with Path.GetTempPath or in the environment variable %TEMP%.

**Comment by Root-MtX** [comment]
This is something I’ve been meaning to change but have been lazy. I will fix it and push an update soon. Originally with older versions with devkitpro it would error out Makefile if a space was in a directory. This isn’t needed anymore.

**Comment by Root-MtX** [comment]
Should be fixed!
