### ISSUE TITLE
Error when trying to compile

### ISSUE THREAD

**Issue by haywire27** [Root-MtX/Nro2Nsp#17]
When I try to compile, I get an error message with the following log message:
Is this because I am running the nro2nsp.exe from E:\ instead of C:\?
As far as I can tell, my keys.dat file has master key 07 ending in ***1B0E placed in the "Resources" folder

--------------------------
Keys loaded from : ./Resources/keys.dat
--------------------------
App Name = Freeset
Author = _JK
Version =  1.0.0
Title Id = 0535B3C31D680000
Standard Forwarder = True
Retro Rom Forwarder = False
Line = sdmc:
SdmcPath = /switch/freeset.nro
RomfsPath = /application.nro
Core Path = /retroarch/cores/core.nro
Rom Path = /Roms/Snes/Super Mario World.smc
NroName = 
NroPath = 

--------------------------
C:\Users\B. Lee/Nro2Nsp/temp/hacbrewpack.exe
C:\Users\B. Lee/Nro2Nsp/temp/keys.dat
C:\Users\B. Lee/Nro2Nsp/temp/control\control.nacp
C:\Users\B. Lee/Nro2Nsp/temp/control\icon_AmericanEnglish.dat
C:\Users\B. Lee/Nro2Nsp/temp/exefs\main
C:\Users\B. Lee/Nro2Nsp/temp/exefs\main.npdm
C:\Users\B. Lee/Nro2Nsp/temp/logo\NintendoLogo.png
C:\Users\B. Lee/Nro2Nsp/temp/logo\StartupMovie.gif
C:\Users\B. Lee/Nro2Nsp/temp/romfs\errorConsole.nro
C:\Users\B. Lee/Nro2Nsp/temp/romfs\nextArgv
C:\Users\B. Lee/Nro2Nsp/temp/romfs\nextNroPath

'C:\Users\B.' is not recognized as an internal or external command,
operable program or batch file.

--------------------------
C:\Users\B. Lee/Nro2Nsp/temp/hacbrewpack.exe
C:\Users\B. Lee/Nro2Nsp/temp/keys.dat
C:\Users\B. Lee/Nro2Nsp/temp/control\control.nacp
C:\Users\B. Lee/Nro2Nsp/temp/control\icon_AmericanEnglish.dat
C:\Users\B. Lee/Nro2Nsp/temp/exefs\main
C:\Users\B. Lee/Nro2Nsp/temp/exefs\main.npdm
C:\Users\B. Lee/Nro2Nsp/temp/logo\NintendoLogo.png
C:\Users\B. Lee/Nro2Nsp/temp/logo\StartupMovie.gif
C:\Users\B. Lee/Nro2Nsp/temp/romfs\errorConsole.nro
C:\Users\B. Lee/Nro2Nsp/temp/romfs\nextArgv
C:\Users\B. Lee/Nro2Nsp/temp/romfs\nextNroPath

**Comment by Root-MtX** [comment]
Looks like I introduced a bug, I’ll fix this. Thanks for letting me know.

**Comment by Root-MtX** [comment]
Fixed and updated release, redownload it please. Sorry for the late release!
