### ISSUE TITLE
Closing hbmenu while running an usb app will crash

### ISSUE THREAD

**Issue by r4dius** [Root-MtX/Nro2Nsp#19]
Not sure if it's something that can be fixed but I had multiple times where tinfoil or goldleaf stopped transferring so I needed to restart the app,
if it was launched thru the hbmenu forwarder and I close it in the home menu with "X" -> "Close" everything just crashes, if I disconnect the usb cable before closing it's ok,
to reproduce :
- run hbmenu forwarder
- run tinfoil or goldleaf nro
- connect to pc with usb
- press home
- press X on hbmenu forwarder and close

I tried with a direct forwarder to goldleaf and same result,
btw I tested the official goldleaf nsp too, it crashes the same way ^^

**Comment by liamadvance** [comment]
This is an issue with the USB system module on 7.0.x. Update to 8.0.1 and it won't crash anymore.
