### ISSUE TITLE
File copying failed. What am i doing wrong?

### ISSUE THREAD

**Issue by rileyvl** [Root-MtX/Nro2Nsp#24]
![ED7838D9-BF80-4447-BD6D-D7500ED2265A](https://user-images.githubusercontent.com/37483888/64732266-f33bf100-d4e2-11e9-83bf-7c9d3e7f3bbf.jpeg)
It says: cant convert some or all of Id references, — file copying failed please make sure the file missing isn’t the “resources” next to the application

**Comment by rileyvl** [comment]
here are my logs:
Nro2Nsp Version: 3.3.4

--------------------------
Preset Settings:
Working Directory: C:\Users\denis/Nro2Nsp/
Preset Author Enable: True
Preset Authot Value: riley
Rolling Id Enable: False
Rolling Id Value: 
Perserve Data Enable: False
Key Generation: 1
Auto Convert Icons: True
Beta Builds Enabled: False
Skipped Builds: False : 0.0.0.0
--------------------------
Inputed Image Information:
Img Path: C:\Users\denis\OneDrive\Bureaublad\bluechompymage.png
Image Extension type: .png
Icon Dimensions: 224x285
Invalid Colour Repersentation: False
--------------------------
Settings Changed:
Working Directory: C:\Users\denis/Nro2Nsp/
Preset Author Enable: True
Preset Authot Value: riley
Rolling Id Enable: False
Rolling Id Value: 
Perserve Data Enable: False
Key Generation: 1
Auto Convert Icons: True
Beta Builds Enabled: False
Skipped Builds: False : 0.0.0.0
--------------------------
Settings Changed:
Working Directory: C:\Users\denis/Nro2Nsp/
Preset Author Enable: True
Preset Authot Value: riley
Rolling Id Enable: False
Rolling Id Value: 
Perserve Data Enable: False
Key Generation: 1
Auto Convert Icons: True
Beta Builds Enabled: False
Skipped Builds: False : 0.0.0.0
--------------------------
Keys loaded from : ./Resources/keys.txt
--------------------------
App Name = App Namebanjo-kazooie
Author = riley
Version =  1.0.0
Title Id = 05303911E5300000
Standard Forwarder = False
Retro Rom Forwarder = True
Line = 
SdmcPath = /switch/application/application.nro
RomfsPath = /application.nro
Core Path = /retroarch/cores/mupen64plus_next_libretro_libnx.nro
Rom Path = /roms/Nintendo - Nintendo 64/Banjo-Kazooie.n64
NroName = 
NroPath = 

--------------------------
C:\Users\denis/Nro2Nsp/temp/keys.dat
C:\Users\denis/Nro2Nsp/temp/control\control.nacp
C:\Users\denis/Nro2Nsp/temp/control\icon_AmericanEnglish.dat
C:\Users\denis/Nro2Nsp/temp/exefs\main
C:\Users\denis/Nro2Nsp/temp/exefs\main.npdm
C:\Users\denis/Nro2Nsp/temp/logo\NintendoLogo.png
C:\Users\denis/Nro2Nsp/temp/logo\StartupMovie.gif
C:\Users\denis/Nro2Nsp/temp/romfs\errorConsole.nro
C:\Users\denis/Nro2Nsp/temp/romfs\nextArgv
C:\Users\denis/Nro2Nsp/temp/romfs\nextNroPath


'"C:\Users\denis/Nro2Nsp/temp/hacbrewpack.exe"' is not recognized as an internal or external command,
operable program or batch file.

--------------------------
C:\Users\denis/Nro2Nsp/temp/keys.dat
C:\Users\denis/Nro2Nsp/temp/control\control.nacp
C:\Users\denis/Nro2Nsp/temp/control\icon_AmericanEnglish.dat
C:\Users\denis/Nro2Nsp/temp/exefs\main
C:\Users\denis/Nro2Nsp/temp/exefs\main.npdm
C:\Users\denis/Nro2Nsp/temp/logo\NintendoLogo.png
C:\Users\denis/Nro2Nsp/temp/logo\StartupMovie.gif
C:\Users\denis/Nro2Nsp/temp/romfs\errorConsole.nro
C:\Users\denis/Nro2Nsp/temp/romfs\nextArgv
C:\Users\denis/Nro2Nsp/temp/romfs\nextNroPath

--------------------------
Settings Changed:
Working Directory: C:\Users\denis/Nro2Nsp/
Preset Author Enable: True
Preset Authot Value: riley
Rolling Id Enable: False
Rolling Id Value: 
Perserve Data Enable: False
Key Generation: 1
Auto Convert Icons: True
Beta Builds Enabled: False
Skipped Builds: False : 0.0.0.0
--------------------------
Keys loaded from : ./Resources/keys.txt
--------------------------
App Name = App Namebanjo-kazooie
Author = riley
Version =  1.0.0
Title Id = 05303911E5300000
Standard Forwarder = False
Retro Rom Forwarder = True
Line = 
SdmcPath = /switch/application/application.nro
RomfsPath = /application.nro
Core Path = /retroarch/cores/mupen64plus_next_libretro_libnx.nro
Rom Path = /roms/Nintendo - Nintendo 64/Banjo-Kazooie.n64
NroName = 
NroPath = 

--------------------------
C:\Users\denis/Nro2Nsp/temp/keys.dat
C:\Users\denis/Nro2Nsp/temp/control\control.nacp
C:\Users\denis/Nro2Nsp/temp/control\icon_AmericanEnglish.dat
C:\Users\denis/Nro2Nsp/temp/exefs\main
C:\Users\denis/Nro2Nsp/temp/exefs\main.npdm
C:\Users\denis/Nro2Nsp/temp/logo\NintendoLogo.png
C:\Users\denis/Nro2Nsp/temp/logo\StartupMovie.gif
C:\Users\denis/Nro2Nsp/temp/romfs\errorConsole.nro
C:\Users\denis/Nro2Nsp/temp/romfs\nextArgv
C:\Users\denis/Nro2Nsp/temp/romfs\nextNroPath


'"C:\Users\denis/Nro2Nsp/temp/hacbrewpack.exe"' is not recognized as an internal or external command,
operable program or batch file.

--------------------------
C:\Users\denis/Nro2Nsp/temp/keys.dat
C:\Users\denis/Nro2Nsp/temp/control\control.nacp
C:\Users\denis/Nro2Nsp/temp/control\icon_AmericanEnglish.dat
C:\Users\denis/Nro2Nsp/temp/exefs\main
C:\Users\denis/Nro2Nsp/temp/exefs\main.npdm
C:\Users\denis/Nro2Nsp/temp/logo\NintendoLogo.png
C:\Users\denis/Nro2Nsp/temp/logo\StartupMovie.gif
C:\Users\denis/Nro2Nsp/temp/romfs\errorConsole.nro
C:\Users\denis/Nro2Nsp/temp/romfs\nextArgv
C:\Users\denis/Nro2Nsp/temp/romfs\nextNroPath

--------------------------
Settings Changed:
Working Directory: C:\Users\denis/Nro2Nsp/
Preset Author Enable: True
Preset Authot Value: riley
Rolling Id Enable: False
Rolling Id Value: 
Perserve Data Enable: False
Key Generation: 2
Auto Convert Icons: True
Beta Builds Enabled: False
Skipped Builds: False : 0.0.0.0
--------------------------
Settings Changed:
Working Directory: C:\Users\denis/Nro2Nsp/
Preset Author Enable: True
Preset Authot Value: riley
Rolling Id Enable: False
Rolling Id Value: 
Perserve Data Enable: False
Key Generation: 2
Auto Convert Icons: True
Beta Builds Enabled: False
Skipped Builds: False : 0.0.0.0
--------------------------
Keys loaded from : ./Resources/keys.txt
--------------------------
App Name = App Namebanjo-kazooie
Author = riley
Version =  1.0.0
Title Id = 05303911E5300000
Standard Forwarder = False
Retro Rom Forwarder = True
Line = 
SdmcPath = /switch/application/application.nro
RomfsPath = /application.nro
Core Path = /retroarch/cores/mupen64plus_next_libretro_libnx.nro
Rom Path = /roms/Nintendo - Nintendo 64/Banjo-Kazooie.n64
NroName = 
NroPath = 

--------------------------
C:\Users\denis/Nro2Nsp/temp/keys.dat
C:\Users\denis/Nro2Nsp/temp/control\control.nacp
C:\Users\denis/Nro2Nsp/temp/control\icon_AmericanEnglish.dat
C:\Users\denis/Nro2Nsp/temp/exefs\main
C:\Users\denis/Nro2Nsp/temp/exefs\main.npdm
C:\Users\denis/Nro2Nsp/temp/logo\NintendoLogo.png
C:\Users\denis/Nro2Nsp/temp/logo\StartupMovie.gif
C:\Users\denis/Nro2Nsp/temp/romfs\errorConsole.nro
C:\Users\denis/Nro2Nsp/temp/romfs\nextArgv
C:\Users\denis/Nro2Nsp/temp/romfs\nextNroPath


'"C:\Users\denis/Nro2Nsp/temp/hacbrewpack.exe"' is not recognized as an internal or external command,
operable program or batch file.

--------------------------
C:\Users\denis/Nro2Nsp/temp/keys.dat
C:\Users\denis/Nro2Nsp/temp/control\control.nacp
C:\Users\denis/Nro2Nsp/temp/control\icon_AmericanEnglish.dat
C:\Users\denis/Nro2Nsp/temp/exefs\main
C:\Users\denis/Nro2Nsp/temp/exefs\main.npdm
C:\Users\denis/Nro2Nsp/temp/logo\NintendoLogo.png
C:\Users\denis/Nro2Nsp/temp/logo\StartupMovie.gif
C:\Users\denis/Nro2Nsp/temp/romfs\errorConsole.nro
C:\Users\denis/Nro2Nsp/temp/romfs\nextArgv
C:\Users\denis/Nro2Nsp/temp/romfs\nextNroPath

--------------------------
Settings Changed:
Working Directory: C:\Users\denis/Nro2Nsp/
Preset Author Enable: True
Preset Authot Value: riley
Rolling Id Enable: False
Rolling Id Value: 
Perserve Data Enable: False
Key Generation: 1
Auto Convert Icons: True
Beta Builds Enabled: False
Skipped Builds: False : 0.0.0.0
--------------------------
Keys loaded from : ./Resources/keys.dat
--------------------------
App Name = App Namebanjo-kazooie
Author = riley
Version =  1.0.0
Title Id = 05303911E5300000
Standard Forwarder = False
Retro Rom Forwarder = True
Line = 
SdmcPath = /switch/application/application.nro
RomfsPath = /application.nro
Core Path = /retroarch/cores/mupen64plus_next_libretro_libnx.nro
Rom Path = /roms/Nintendo - Nintendo 64/Banjo-Kazooie.n64
NroName = 
NroPath = 

--------------------------
C:\Users\denis/Nro2Nsp/temp/keys.dat
C:\Users\denis/Nro2Nsp/temp/control\control.nacp
C:\Users\denis/Nro2Nsp/temp/control\icon_AmericanEnglish.dat
C:\Users\denis/Nro2Nsp/temp/exefs\main
C:\Users\denis/Nro2Nsp/temp/exefs\main.npdm
C:\Users\denis/Nro2Nsp/temp/logo\NintendoLogo.png
C:\Users\denis/Nro2Nsp/temp/logo\StartupMovie.gif
C:\Users\denis/Nro2Nsp/temp/romfs\errorConsole.nro
C:\Users\denis/Nro2Nsp/temp/romfs\nextArgv
C:\Users\denis/Nro2Nsp/temp/romfs\nextNroPath


'"C:\Users\denis/Nro2Nsp/temp/hacbrewpack.exe"' is not recognized as an internal or external command,
operable program or batch file.

--------------------------
C:\Users\denis/Nro2Nsp/temp/keys.dat
C:\Users\denis/Nro2Nsp/temp/control\control.nacp
C:\Users\denis/Nro2Nsp/temp/control\icon_AmericanEnglish.dat
C:\Users\denis/Nro2Nsp/temp/exefs\main
C:\Users\denis/Nro2Nsp/temp/exefs\main.npdm
C:\Users\denis/Nro2Nsp/temp/logo\NintendoLogo.png
C:\Users\denis/Nro2Nsp/temp/logo\StartupMovie.gif
C:\Users\denis/Nro2Nsp/temp/romfs\errorConsole.nro
C:\Users\denis/Nro2Nsp/temp/romfs\nextArgv
C:\Users\denis/Nro2Nsp/temp/romfs\nextNroPath

**Comment by Root-MtX** [comment]
Try this beta build https://github.com/Root-MtX/Nro2Nsp/blob/master/Releases/Betas/Nro2Nsp%203.3.5%20-%20Beta%203.zip
