### ISSUE TITLE
Nsp created titles do not work anymore on firmware 9.0

### ISSUE THREAD

**Issue by ginkuji** [Root-MtX/Nro2Nsp#25]
All the nsp created titles refuse to recognize button inputs.
The hombrew apps were also tested running the official homebrew menu legal nsp. Running them on the legal nsp makes them work normally

**Comment by M-Teix** [comment]
It’s something I’m aware of and will fix, unfortunately due to the changes in 9.0.0 it’ll require you to make new ones

**Comment by ginkuji** [comment]
Ok thanks

**Comment by Root-MtX** [comment]
https://github.com/Root-MtX/Nro2Nsp/releases/tag/3.3.5
note: that nros you forward too will need to be compiled with newest libnx changes for 9.0.0 to work

**Comment by StiefelHD** [comment]
I have a problem, when i use the RetroArch forwarder, i cant use the controll...
But in RetroArch works.

In 9.0.0, i use the newest stable and beta version.
