### ISSUE TITLE
OldTitleKeyEnable not found

### ISSUE THREAD

**Issue by RedSparr0w** [Root-MtX/Nro2Nsp#31]
OS: `Windows 10`
Version: `3.3.6-Beta1`

When clicking compile, the following error occurs:

![image](https://user-images.githubusercontent.com/7288322/73698525-40e12080-4746-11ea-9fe9-2fa4a5d5537e.png)

**Comment by Root-MtX** [comment]
https://www.dropbox.com/s/wz7hgt42zp8w3lf/Settings.xml?dl=0
Try importing this settings.xml in the settings menu. Looks like its mad that a feature was removed that was prev enabled.

**Comment by Root-MtX** [comment]
Let me know if that doesnt help!

**Comment by RedSparr0w** [comment]
👍 Awesome, that seems to solve the problem!
