### ISSUE TITLE
Rolling title ID not working

### ISSUE THREAD

**Issue by RedSparr0w** [Root-MtX/Nro2Nsp#33]
OS: `Windows 10`
Version: `3.3.6-Beta1`

The rolling title ID setting doesn't appear to be working.

**NOTE:**
_Wasn't sure how it was supposed to work, so tried it on an older version, but doesn't seem to function the same._

**Comment by Root-MtX** [comment]
Will check that out. Thanks for letting me know.

**Comment by Root-MtX** [comment]
Should be fixed now in 3.3.6 beta 2. Thanks for letting me know about it and let me know if an issue still occurs
