### ISSUE TITLE
master_key_00

### ISSUE THREAD

**Issue by deejay87** [Root-MtX/Nro2Nsp#35]
Hello
**3.3.6 beta 3**
Got this problem when Compile

> "master_key_00" doesnt appear to have the
> correct value, please correct this key or build errors may occur

No problem with the previous releases

**Comment by Root-MtX** [comment]
Is it possible your master key value is incorrect? Older versions never actually checked the key files for proper keys. Try changing your key generation in settings and see if other master keys fail the checks too

**Comment by deejay87** [comment]
Strange, cause i use lot of programs, like nsc_builder, renpack, and test 3 keys files and never have problem (i make lot of tests), and it's only this release who don't work

**Comment by Root-MtX** [comment]
i mean it is possible that its a bug on my end, any way your able to message me on discord MtX#2980

**Comment by Root-MtX** [comment]
Ive spotted the issue, overlooked my checks and appears to be case sensitive. Will fix this soon, changeing letters to capitals for the required keys in the keys_template will temp solve this.

**Comment by Root-MtX** [comment]
3.3.6 Beta 4 is out and this should be fixed now. Thanks for the help!
