### ISSUE TITLE
Wiki update for application use

### ISSUE THREAD

**Issue by Pitta** [Root-MtX/Nro2Nsp#37]
After finally having success last night, i pulled down the wiki and updated the Use.md page.  Happy to send it to someone on discord or push the change myself if given wiki access control. It's on its own branch for review.

**Comment by Pitta** [comment]
Bump....?

**Comment by Root-MtX** [comment]
Hey sorry, been tied up these days. Id like that, either push a pull request or send to me in discord to review

**Comment by Pitta** [comment]
No worries - reached out on discord via PM. Happy to contribute back when I can for projects I find useful. ;-)
