### ISSUE TITLE
Import info from NRO

### ISSUE THREAD

**Issue by chronoss09** [Root-MtX/Nro2Nsp#6]
I test the last version and many .nro to import all info from .nro but nothing work. NRO tested : 
- Mame
- n1dus
- NX-Shell
- SX Dumper
- Tinfoil
- WAINDUMPER
The log pik any info from them and give me an error
![748e605a76697ae14ea6203e5454e1c2](https://user-images.githubusercontent.com/17669980/48695709-20c84e80-ebe0-11e8-8dbf-fecd4631e18b.png)
![2dc487700a02c3ad46d3f4b0c9a9f441](https://user-images.githubusercontent.com/17669980/48695710-2160e500-ebe0-11e8-9310-b2b0fdfc6b3c.png)
Thanks for this great last version and hope you will fix it !

**Comment by matt-teix** [comment]
What’s your system details, os, 32/64bit? Can you send me you log from the resources as well

**Comment by matt-teix** [comment]
Also if possible can you translate your error messages please

**Comment by chronoss09** [comment]
System W7 64bit
Error mean the log crash and today i have this error : 

![5e85a71ced594c1e68645a15377a6958](https://user-images.githubusercontent.com/17669980/48754257-511bf580-ec91-11e8-933d-c460a579e78e.png)

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentException: Parameter is not valid.
   at System.Drawing.Bitmap..ctor(String filename)
   at MtX.Control.IconImport.IconConvert(String Input)
   at MtX.Control.ImportMeta.GetIcon()
   at MtX.Nro2Nsp.Nro.RadioButton_Checked(Object sender, EventArgs e)
   at System.Windows.Forms.RadioButton.OnCheckedChanged(EventArgs e)
   at System.Windows.Forms.RadioButton.set_Checked(Boolean value)
   at System.Windows.Forms.RadioButton.OnClick(EventArgs e)
   at System.Windows.Forms.RadioButton.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3062.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
Nro2Nsp
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///D:/Hack/Switch/Create%20NSP/Nro2Nsp/Nro2Nsp_v3.0/Nro2Nsp.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3062.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3062.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3062.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
MtX.Control
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///D:/Hack/Switch/Create%20NSP/Nro2Nsp/Nro2Nsp_v3.0/MtX.Control.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3062.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3081.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3062.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

Log file on resource folder, i have this : 
Preset Settings:
Custom Devkit Enable: False
Custom Devkit Path: 
Preset Author Enable: False
Preset Authot Value: 
Rolling Id Enable: False
Rolling Id Value: 
Perserve Data Enable: False
Old Style Title Key Enable: False

Imported Nro AppName: 
Imported Nro Author: 
Imported Nro Version:

**Comment by matt-teix** [comment]
I found this documentation about compatibility issues with windows 7, there appears to be an update that may resolve this. Can you please verify this update has been performed. KB2999226

“Microsoft has moved to a new Universal C runtime with Visual Studio 2015. The promise is, that there won’t be any new, incompatible Visual C runtimes anymore for each Visual Studio product generation. Builds for this new UCRT don’t depend on a specific vcredist anymore, but a new runtime. This runtime is part of

Windows 10 (starting with the first version/edition) and Windows Server 2016

the Windows update KB2999226 for any older Windows version

vcredist 2015 and 2017, which contains the above Windows update

**Comment by matt-teix** [comment]
Any luck?

**Comment by chronoss09** [comment]
sorry, can't update my pc to know if it working :(

**Comment by matt-teix** [comment]
I can maybe try and recompile nstool differently and send you a test build
