### ISSUE TITLE
NSP with Romfs crashes the switch

### ISSUE THREAD

**Issue by shyim** [Root-MtX/Nro2Nsp#7]
If i bundle the nro file using Romfs, my switch is crashing. Firmware: 6.2. With SDMC is working

**Comment by matt-teix** [comment]
What nro?

**Comment by shyim** [comment]
That old tinfoil

**Comment by Root-MtX** [comment]
Original tinfoil doesn't work in romfs, use sdmc for that. Ive only looked into it briefly but I believe its do to how the nro handles paths. In romfs it doesn't have access to the romfs of the nsp.

**Comment by niko1point0** [comment]
This happened to me too. I built a game NRO that has textures in Romfs, then I tried to put that NRO into the NSP's romfs, and it crashed @Root-MtX @shyim

**Comment by TRBZN61** [comment]
Solved that problem myself:
Thumbnails have to be .jpg and porpotional ex.: 100x100; 256x256; 300x300

![01](https://user-images.githubusercontent.com/48518356/54279490-7e204b00-4595-11e9-8ab2-51cf19a9daad.jpg)
![02](https://user-images.githubusercontent.com/48518356/54279491-7e204b00-4595-11e9-8bf4-e2ab3a9f3d76.jpg)

**Comment by Root-MtX** [comment]
It appears to be an issue with the image conversion with sxos? I have not seen this happen before

**Comment by TRBZN61** [comment]
yes i think so, because after I made the pictures proportional, everything worked fine for me :D
