### ISSUE TITLE
Option to disable black bars and logos ?

### ISSUE THREAD

**Issue by r4dius** [Root-MtX/Nro2Nsp#9]
Hi,

some homebrew apps launch without the top and bottom black bars (with logos),
would it be possible to have an option to enable / disable this in nro2nsp ? (I'm not sure how it's done)

Thanks :)

**Comment by Root-MtX** [comment]
Do you mean the “licensed” by and “Nintendo” parts on startup?

**Comment by Root-MtX** [comment]
If so the logos are In the ./resources folder and can be changed to your liking

**Comment by r4dius** [comment]
Sorry for the lack of info, yes I mean the nintendo logo and the switch animated gif but the reason I say that is because I have an nsp launcher for hbmenu I got from gbatemp that launches hbmenu without logos nor the black bars (don't know how it was built),
when I build one with nro2nsp, it runs with the logos on black bars on top and bottom and then they disappear, I guess if I just put empty logos I'll still get those black bars, so I suppose their is some method to disable them completely like the other nsp launcher ^^

**Comment by Root-MtX** [comment]
I could add an option in a future build for —nologos.

**Comment by Root-MtX** [comment]
Added. It will be included in the next beta. It should pop up here this week.

**Comment by r4dius** [comment]
Thanks :)

**Comment by Root-MtX** [comment]
No Problem, keep an eye out for tonight/tomrrow as ill post the next beta of goodies up.
